### ISSUE TITLE
2.1 pvec

### ISSUE THREAD

**Issue by Ra0R** [tux19/cpp16#17]
Somehow pvec doesn't seem to work for me:
pvector<string> dict(argv[1]);

overwrites the file given by argv[1] with:
"SS
0
0"

**Comment by tux19** [comment]
musst template typ angeben ...

also in der main

pvector<int> blubb("asdfDSF.txt"

im Code pvector<T> foo

je nach dem für was du ihn brauchst... 

ich teste gleich noch mal

**Comment by Ra0R** [comment]
Oh whoops, habs oben vergessen aber im code so gemacht:
    pvector<string> dictV(argv[1]);
    pvector<string> textV(argv[2]));

**Comment by Ra0R** [comment]
Hat sich erledigt, muss eine pset<T> klasse implementieren.
